service: sls-golang-lambda-provided-al2

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  timeout: 120
  runtime: provided.al2

plugins:
  - serverless-go-plugin

custom:
  go:
    cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

functions:
  hello-world:
    handler: ./src/hello-world
    url: true
  hello-world2:
    handler: ./src/hello-world2
    url: true
