service: sls-golang-lambda-provided-al2

frameworkVersion: '3'

provider:
  name: aws
  region: ap-northeast-1
  timeout: 120
  runtime: provided.al2
  stage: ${opt:stage, 'dev'}
  environment: ${file(./src/config/config.${self:provider.stage}.yml)}

plugins:
  - serverless-go-plugin

custom:
  go:
    cmd: GOARCH=amd64 GOOS=linux go build -ldflags="-s -w"
    supportedRuntimes: ["provided.al2"]
    buildProvidedRuntimeAsBootstrap: true

functions:
  hello-world:
    handler: ./src/hello-world
    url: true
  hello-world2:
    handler: ./src/hello-world2
    url: true
    environment:
      APP_ENV: "dev2"
  show-env:
    handler: ./src/show-env
    url: true
    environment: ${file(./src/config/server_config.${self:provider.stage}.yml)}
